// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NestedModuleTests
    {
        const string __DllName = "csbindgen_tests_nested_module";



        [DllImport(__DllName, EntryPoint = "triple_input", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int triple_input(NumberStruct input);

        [DllImport(__DllName, EntryPoint = "triple_input_aliased", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int triple_input_aliased(NumberStruct input);

        [DllImport(__DllName, EntryPoint = "number_map", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int number_map(NumberEnum input);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct NumberStruct
    {
        public int num;
    }


    internal enum NumberEnum : byte
    {
        One,
        Two,
        Three,
    }


}
    