// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Vec3
    {
        public float x;
        public float y;
        public float z;
    }


    internal enum Foo : uint
    {
        Bar = 1,
        Baz = 2,
    }


}
